defaults: &defaults
  adapter: mysql2
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock
  pool: 10
  encoding: utf8
  collation: utf8_general_ci

development:
  <<: *defaults
  database: easyinstall_dev

test:
  <<: *defaults
  database: easyinstall_test
  pool: 1
  set:
    sql_mode: traditional